#!/usr/bin/env bash
#
wallpapers="$HOME/.config/home-manager/hyprland/Wallpapers/"

list_wallpapers() {
    for file in "$1"/*
    do
        if [[ -f "$file" ]]; then
            echo -en "$(basename "$file")\0icon\x1f$(realpath "$file")\n"
        fi
    done
}

selected_wallpaper="$(list_wallpapers ${wallpapers} |  rofi -dmenu -theme ~/.config/rofi/launchers/type-4/wallpaper-selector.rasi -p " ")"

if [[ -f "$selected_wallpaper" ]]; then
    exit 0;
fi

swww img ${wallpapers}"${selected_wallpaper}"
