#!/bin/sh 

# Start Wallpaper
swww init
swww img $HOME/.config/home-manager/hyprland/Wallpapers/shinobu_night.png &

# Start dunst
dunst &

# Start foot server 
foot --server &

# Start waybar
waybar
